name: Update BSB Directory and Prefix Files
env:
  GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}

on:
  schedule:
    # https://crontab.guru/every-month
    # At 00:00 on day-of-month 1.
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    name: Update BSB CSVs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Update BSB CSVs
        id: update-csvs
        run: python .github/workflows/scripts/csv_update.py
      - id: get-date
        run: echo "date=$(date +'%B-%Y')" >> $GITHUB_OUTPUT
      - uses: peter-evans/create-pull-request@v6
        id: raise-pr
        with:
          branch: "bot/automate-ftp/${{ steps.get-date.outputs.date }}"
          title: "chore: update bsb directory with ${{ steps.get-date.outputs.date }} data"
          commit-message: "chore: update bsb directory with ${{ steps.get-date.outputs.date }} data"
          body: "Updated csv files using files: ${{ steps.update-csvs.outputs.bsb_prefix_file }}\n
                  and ${{ steps.update-csvs.outputs.bsb_directory_file }}.\n\n
                  Auto-generated by create-pull-request:\t[https://github.com/peter-evans/create-pull-request]"
          committer: GitHub Actions <actions@github.com>
          signoff: false
          delete-branch: true
